// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogO4StAspJKmarN7HpBcRzrUd3ozGhKM',
    appId: '1:236428171454:web:33b0e5e184b601396c66ef',
    messagingSenderId: '236428171454',
    projectId: 'en-practice',
    authDomain: 'en-practice.firebaseapp.com',
    storageBucket: 'en-practice.firebasestorage.app',
    measurementId: 'G-Z27Q2RDKWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fZnQy3V59O36QrcmDMT11HNog1XTero',
    appId: '1:236428171454:android:1c838c4855d3f5146c66ef',
    messagingSenderId: '236428171454',
    projectId: 'en-practice',
    storageBucket: 'en-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddyWIbxurMoh9Cy53NwIF_IXVKpqPJtg',
    appId: '1:236428171454:ios:328d29c475e023416c66ef',
    messagingSenderId: '236428171454',
    projectId: 'en-practice',
    storageBucket: 'en-practice.firebasestorage.app',
    iosBundleId: 'com.swpts.enpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBddyWIbxurMoh9Cy53NwIF_IXVKpqPJtg',
    appId: '1:236428171454:ios:3231defa2a4c333c6c66ef',
    messagingSenderId: '236428171454',
    projectId: 'en-practice',
    storageBucket: 'en-practice.firebasestorage.app',
    iosBundleId: 'com.example.enpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCogO4StAspJKmarN7HpBcRzrUd3ozGhKM',
    appId: '1:236428171454:web:33b0e5e184b601396c66ef',
    messagingSenderId: '236428171454',
    projectId: 'en-practice',
    authDomain: 'en-practice.firebaseapp.com',
    storageBucket: 'en-practice.firebasestorage.app',
    measurementId: 'G-Z27Q2RDKWG',
  );

}